<strong><?php esc_html_e('Monday', 'bab'); ?></strong>
<span><?php echo esc_html($post->monday) ?></span>
<strong><?php esc_html_e('Tuesday', 'bab'); ?></strong>
<span><?php echo esc_html($post->tuesday) ?></span>
<strong><?php esc_html_e('Wednesday', 'bab'); ?></strong>
<span><?php echo esc_html($post->wednesday) ?></span>
<strong><?php esc_html_e('Thursday', 'bab'); ?></strong>
<span><?php echo esc_html($post->thursday) ?></span>
<strong><?php esc_html_e('Friday', 'bab'); ?></strong>
<span><?php echo esc_html($post->friday) ?></span>
<strong><?php esc_html_e('Saturday', 'bab'); ?></strong>
<span><?php echo esc_html($post->saturday) ?></span>
<strong><?php esc_html_e('Sunday', 'bab'); ?></strong>
<span><?php echo esc_html($post->sunday) ?></span>